const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
  const page = await browser.newPage();
  const base = process.env.BILLING_ORIGIN || 'http://127.0.0.1:18089';
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/pageview', route => route.fulfill({ json: {} }));
  await page.goto(base + '/plus');
  await page.getByRole('button', { name: 'Prijavi se', exact: true }).waitFor();
  assert.match(await page.locator('main').innerText(), /7,90/);
  assert.doesNotMatch(await page.locator('main').innerText(), /19,00|365|12 mjeseci/);
  let status = { active: false, hasCustomer: false, status: 'none' };
  await page.route('**/api/billing/status', route => route.fulfill({ json: status }));
  await page.route('**/api/auth/me', route => route.fulfill({ json: { authenticated: true, user: { id: 'test', email: 'unit@example.invalid', createdAt: '2026-01-01' } } }));
  await page.goto(base + '/plus');
  await page.getByRole('button', { name: 'Pretplati se', exact: true }).waitFor();
  status = { active: true, hasCustomer: true, status: 'active', premiumUntil: '2027-01-01', cancelAtPeriodEnd: true };
  await page.goto(base + '/profil');
  await page.getByRole('button', { name: 'Odi na Matura Plus', exact: true }).waitFor();
  assert.equal(await page.locator('.profile-plus-panel').getAttribute('data-billing-active'), 'true');
  assert.equal(await page.locator('.profile-plus-panel [role="status"]').evaluate(element => getComputedStyle(element, '::after').content), '"✓"');
  assert.equal(await page.getByRole('link', { name: 'O Maturi Plus' }).count(), 0);
  assert.equal(await page.getByRole('link', { name: 'Pregledaj račune' }).count(), 1);
  assert.match(await page.locator('[data-billing]').innerText(), /Obnova je otkazana/);
  await page.route('**/api/billing/portal', route => route.fulfill({ status: 503, json: { error: 'Probna greška portala' } }));
  await page.getByRole('link', { name: 'Pregledaj račune' }).click();
  await page.getByText('Probna greška portala', { exact: true }).waitFor();
  assert.equal(await page.getByRole('link', { name: 'Pregledaj račune' }).getAttribute('aria-disabled'), null);
  await page.getByRole('button', { name: 'Odi na Matura Plus' }).click();
  await page.waitForURL(base + '/plus');
  await page.getByRole('button', { name: 'Upravljaj pretplatom' }).click();
  await page.getByText('Probna greška portala', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Upravljaj pretplatom' }).isEnabled(), true);
  status = { active: false, hasCustomer: false, status: 'none' };
  await page.goto(base + '/profil');
  await page.getByText('Matura Plus nije aktivan.', { exact: true }).waitFor();
  assert.equal(await page.locator('.profile-plus-panel').getAttribute('data-billing-active'), 'false');
  assert.equal(await page.locator('.profile-plus-panel [role="status"]').evaluate(element => getComputedStyle(element, '::after').content), '"×"');
  assert.equal(await page.getByRole('button', { name: 'Odi na Matura Plus' }).count(), 1);
  status = { active: false, hasCustomer: true, status: 'past_due' };
  await page.goto(base + '/plus');
  await page.getByText('Naplata nije dovršena.', { exact: false }).waitFor();
  assert.equal(await page.getByRole('link', { name: 'Pregledaj račune' }).count(), 1);
  status = { active: false, hasCustomer: true, status: 'none' };
  await page.goto(base + '/plus?success=1');
  await page.getByText('Čekamo potvrdu plaćanja.', { exact: false }).waitFor();
  assert.equal(await page.locator('[data-billing] .primary-button').isEnabled(), false);
  status = { active: true, hasCustomer: true, status: 'active', premiumUntil: '2027-01-01' };
  await page.getByRole('button', { name: 'Upravljaj pretplatom' }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '/tmp/matura-plus-mobile.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('Billing browser flows passed: login, purchase, profile, cancellation, API error, payment pending, activation, mobile layout.');
})().catch(error => { console.error(error); process.exitCode = 1; });
