const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const base = process.env.MEDICINE_ORIGIN || 'http://127.0.0.1:8092';
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/**', route => route.fulfill({ json: {} }));
  await page.goto(base + '/?predmet=Prijemni%20za%20medicinu');
  await page.getByRole('heading', { name: 'Katalog pitanja', exact: true }).waitFor();
  assert.equal(await page.locator('.practice-exam-row').count(), 4);
  assert.deepEqual(await page.locator('.medicine-admission__materials h3').allTextContents(), ['Nasumični ispit', 'Katalog pitanja']);
  assert.equal(await page.locator('.medicine-admission__materials').nth(0).locator('a[href*="nacin=simulacija"]').count(), 1);
  assert.equal(await page.locator('.medicine-admission__materials').nth(1).locator('a[href*="nacin=simulacija"]').count(), 0);
  assert.match(await page.locator('.medicine-admission__guide').innerText(), /330\/600.*16\/40/s);
  assert.equal(await page.locator('.medicine-admission a[href*="exam=exam-2020"]').count(), 0);
  assert.equal(await page.locator('.site-footer').getByText('Ispitni materijali:').count(), 0);
  const centered = await page.locator('.medicine-admission .subject-title-row').evaluate((heading) => {
    const box = heading.getBoundingClientRect();
    const parent = heading.closest('.subject-page__intro').getBoundingClientRect();
    return Math.abs((box.left + box.right) / 2 - (parent.left + parent.right) / 2) < 2;
  });
  assert.equal(centered, true);
  assert.match(await page.locator('.medicine-admission').innerText(), /nasumični ispit|Nasumični ispit/);
  assert.match(await page.locator('.medicine-admission').innerText(), /po redu/);
  assert.doesNotMatch(await page.locator('main').innerText(), /Zadatci za upis|priručnik/);

  await page.goto(base + '/medicina.html?exam=biology');
  await page.locator('.solver-header').waitFor();
  assert.equal(await page.locator('.solver-sticky-footer__inner').evaluate((element) => getComputedStyle(element).flexDirection), 'row');
  assert.equal(await page.locator('.question-quickselect__link').count(), 108);
  await page.locator('#med-quickselect [data-quick-question="5"]').click();
  await page.waitForFunction(() => Math.abs(document.querySelector('#pitanje-5').getBoundingClientRect().top) < 50);
  assert.equal(await page.locator('#med-quickselect [aria-current="true"]').getAttribute('data-quick-question'), '5');
  assert.equal(await page.locator('#med-question-jump').inputValue(), '5');
  assert.equal(await page.locator('.med-task').count(), 108);
  assert.equal(await page.locator('.med-task').first().getAttribute('data-question-id'), 'biology-1');
  assert.equal(await page.locator('.med-task').last().getAttribute('data-question-id'), 'biology-108');
  await page.locator('[data-question-id="biology-1"] input[value="E"]').check();
  await page.locator('[data-question-id="biology-1"] [data-self-check]').click();
  assert.match(await page.locator('[data-question-id="biology-1"] .med-feedback').innerText(), /Točno/);
  assert.match(await page.locator('[data-score-summary]').innerText(), /5\/540/);
  await page.reload();
  assert.equal(await page.locator('[data-question-id="biology-1"] input[value="E"]').isChecked(), true);
  const practice = await page.evaluate(() => localStorage.getItem(MedicineCore.storageKey('biology')));
  await page.goto(base + '/medicina.html?exam=biology&nacin=simulacija');
  await page.waitForURL('**/medicina.html?exam=biology');
  assert.equal(await page.locator('.med-task').count(), 108);
  assert.equal(await page.locator('[data-question-id="biology-1"] input[value="E"]').isChecked(), true);
  assert.equal(await page.locator('[data-simulation-confirm]').count(), 0);
  assert.equal(await page.evaluate(() => localStorage.getItem(MedicineCore.storageKey('biology'))), practice);

  await page.goto(base + '/medicina.html?exam=exam-2020');
  assert.equal(await page.locator('.med-task').count(), 40);
  await page.locator('[data-question-id="exam-2020-1"] input[value="C"]').check();
  await page.locator('.solver-header [data-subject="Kemija"]').click();
  assert.equal(await page.locator('.med-task').count(), 40);
  assert.equal(await page.locator('.med-task').first().getAttribute('data-question-id'), 'exam-2020-81');
  assert.match(await page.locator('[data-answer-progress]').innerText(), /1\/120/);
  await page.locator('[data-finish]').click();
  assert.match(await page.locator('.exam-results-dialog').innerText(), /5\/600/);
  await page.keyboard.press('Escape');
  await page.locator('.solver-header [data-subject="Biologija"]').click();
  assert.match(await page.locator('[data-question-id="exam-2020-1"] .med-feedback').innerText(), /Točno/);

  await page.goto(base + '/medicina.html?exam=random-120');
  assert.equal(await page.locator('.med-task').count(), 40);
  const first = await page.locator('.med-task').evaluateAll(nodes => nodes.map(node => node.dataset.questionId));
  assert.equal(await page.evaluate(() => localStorage.getItem(MedicineCore.storageKey('random-120'))), null);
  await page.locator('.med-task').first().locator('input[value="A"]').check();
  await page.reload();
  assert.deepEqual(await page.locator('.med-task').evaluateAll(nodes => nodes.map(node => node.dataset.questionId)), first);
  await page.once('dialog', dialog => dialog.accept());
  await page.locator('[data-reset]').click();
  // A fresh simulation must not load the saved practice selection or answers.
  await page.goto(base + '/medicina.html?exam=random-120&nacin=simulacija');
  await page.locator('[data-simulation-confirm]').click();
  assert.equal(await page.locator('.med-task input:checked').count(), 0);
  assert.equal(await page.locator('.med-task').count(), 40);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('#med-question-jump').isVisible(), true);
  await page.locator('#med-question-jump').selectOption('7');
  await page.waitForFunction(() => Math.abs(document.querySelector('#pitanje-7').getBoundingClientRect().top) < 50);
  assert.equal(await page.locator('#med-quickselect [aria-current="true"]').getAttribute('data-quick-question'), '7');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.goto(base + '/medicina.html');
  await page.waitForURL('**/?predmet=Prijemni%20za%20medicinu');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await page.locator('.medicine-admission__materials').count(), 2);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: medicine guide, catalog without simulation, scrolling solver, random paper, practice persistence, simulation isolation, scoring and mobile layout.');
})().catch(error => { console.error(error); process.exitCode = 1; });
