"""Build the local Phosphor subset. Run only when changing the icon selection."""
import json
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from urllib.request import urlopen
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
REVISION = '2b75f3ad12b420c9504ef05df8d2564a28f8500e'
BASE = f'https://raw.githubusercontent.com/phosphor-icons/core/{REVISION}'
# Existing UI names remain supported for older cached pages and scripts.
ALIASES = {
    'amphora': 'potted-plant', 'binary': 'binary', 'circle-check': 'check-circle',
    'triangle-alert': 'warning', 'earth': 'globe-hemisphere-west',
    'eye-off': 'eye-slash', 'flask-conical': 'flask', 'history': 'scroll',
    'house': 'house', 'landmark': 'bank', 'languages': 'translate',
    'library': 'books', 'lightbulb': 'lightbulb', 'music-2': 'headphones',
    'omega': 'function', 'rotate-ccw': 'arrow-counter-clockwise',
    'scale': 'scales', 'sigma': 'sigma', 'users-round': 'users-three',
    'workflow': 'flow-arrow', 'zoom-in': 'magnifying-glass-plus', 'zoom-out': 'magnifying-glass-minus',
}
NAMES = sorted(set(ALIASES.values()) | set('arrow-left arrow-right atom book-open book-open-text camera brain church clock moon cookie dna eye list-checks palette star stethoscope wrench x chat-circle user-circle sun arrow-square-out coffee github-logo download-simple envelope caret-left caret-right play pause speaker-high speaker-slash'.split()))


def fetch(name):
    with urlopen(f'{BASE}/assets/duotone/{name}-duotone.svg', timeout=30) as response:
        svg = response.read().decode()
    root = ET.fromstring(svg)
    assert root.attrib['viewBox'] == '0 0 256 256'
    body = svg[svg.index('>') + 1:svg.rindex('</svg>')]
    return name, body


def main():
    with ThreadPoolExecutor(max_workers=8) as pool:
        icons = dict(pool.map(fetch, NAMES))
    # Language badges adapt Phosphor's chat-circle with outlined EN/DE lettering.
    letters = {
        'english': 'M112 100H80V152H112M80 126H106M136 152V100L176 152V100',
        'german': 'M76 100V152H92C124 152 124 100 92 100ZM176 100H144V152H176M144 126H170',
    }
    for language, path in letters.items():
        icons[f'language-{language}'] = icons['chat-circle'] + f'<path d="{path}" fill="none" stroke="currentColor" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>'
    for alias, name in ALIASES.items():
        icons[alias] = icons[name]
    icons = dict(sorted(icons.items()))
    # A group owns paint, so existing outline-icon CSS cannot override Phosphor fills.
    sprite = '<svg xmlns="http://www.w3.org/2000/svg">\n<!-- Phosphor Icons (MIT); see THIRD_PARTY_NOTICES.md. -->\n'
    for name, body in icons.items():
        sprite += f'<symbol id="{name}" viewBox="0 0 24 24"><g transform="scale(0.09375)" fill="currentColor" stroke="none">{body}</g></symbol>\n'
    sprite += '</svg>\n'
    bundle = '''// Generated by scripts/build_phosphor_icons.py. Phosphor Icons (MIT).
(() => {
  const icons = ICON_DATA;
  function escapeAttribute(value) {
    return String(value ?? "").replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
  }
  window.renderPhosphorIcon = (name, className = "") => {
    const body = icons[name] || icons["book-open"];
    return `<svg class="${escapeAttribute(className)}" aria-hidden="true" focusable="false" viewBox="0 0 24 24"><g transform="scale(0.09375)" fill="currentColor" stroke="none">${body}</g></svg>`;
  };
  // Compatibility for cached pages referencing the previous renderer.
  window.renderLucideIcon = window.renderPhosphorIcon;
})();
'''.replace('ICON_DATA', json.dumps(icons, ensure_ascii=False, indent=2))
    (ROOT / 'assets/phosphor-icons.js').write_text(bundle)
    (ROOT / 'assets/phosphor-icons.svg').write_text(sprite)
    (ROOT / 'lucide-icons.js').write_text(bundle)
    (ROOT / 'assets/lucide-icons.svg').write_text(sprite)
    with urlopen(f'{BASE}/LICENSE', timeout=30) as response:
        (ROOT / 'assets/phosphor/LICENSE').write_bytes(response.read())
    print(f'Built {len(icons)} icons (including compatibility aliases).')


if __name__ == '__main__':
    main()
